name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      sync_edge_to_normal:
        description: 'Sync edge to normal before building'
        type: boolean
        default: false
        required: false

jobs:
  update-edge:
    uses: ./.github/workflows/update-build.yaml
    with:
      addon: carconnectivity-addon-edge
    secrets: inherit

  autotag:
    needs: update-edge
    uses: ./.github/workflows/autotag.yml
    secrets: inherit

  build-edge:
    needs: update-edge
    uses: ./.github/workflows/builder.yml
    with:
      addon: carconnectivity-addon-edge
    secrets: inherit

  sync-edge-to-normal:
    if: inputs.sync_edge_to_normal
    needs: update-edge
    uses: ./.github/workflows/sync.yml
    secrets: inherit

  build-normal:
    needs: [update-edge, sync-edge-to-normal]
    if: always() && needs.update-edge.result == 'success' && (needs.sync-edge-to-normal.result == 'success' || needs.sync-edge-to-normal.result == 'skipped')
    uses: ./.github/workflows/builder.yml
    with:
      addon: carconnectivity-addon
    secrets: inherit
