name: Release Pipeline

on:
  workflow_dispatch:

jobs:
  update-edge:
    uses: ./.github/workflows/update-build.yaml
    with:
      addon: carconnectivity-addon-edge
    secrets: inherit

  autotag:
    needs: update-edge
    uses: ./.github/workflows/autotag.yml
    secrets: inherit

  build-edge:
    needs: update-edge
    uses: ./.github/workflows/builder.yml
    with:
      addon: carconnectivity-addon-edge
    secrets: inherit

  sync-edge-to-normal:
    needs: update-edge
    uses: ./.github/workflows/sync.yml
    secrets: inherit

  build-normal:
    needs: sync-edge-to-normal
    uses: ./.github/workflows/builder.yml
    with:
      addon: carconnectivity-addon
    secrets: inherit
