name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      sync_edge_to_normal:
        description: 'Sync edge to normal before building'
        type: boolean
        default: false
        required: false

jobs:
  update-edge:
    uses: ./.github/workflows/update-build.yaml
    with:
      addon: carconnectivity-addon-edge
    secrets: inherit

  autotag-edge:
    needs: update-edge
    uses: ./.github/workflows/autotag.yml
    with:
      target: edge
    secrets: inherit

  build-edge:
    needs: update-edge
    uses: ./.github/workflows/builder.yml
    with:
      addon: carconnectivity-addon-edge
    secrets: inherit

  pre-release-edge:
    needs: [autotag-edge, build-edge]
    uses: ./.github/workflows/pre-release.yml
    with:
      addon: carconnectivity-addon-edge
      prerelease: true
    secrets: inherit

  sync-edge-to-normal:
    if: inputs.sync_edge_to_normal
    needs: update-edge
    uses: ./.github/workflows/sync.yml
    secrets: inherit

  update-normal:
    needs: [update-edge, sync-edge-to-normal]
    if: always() && needs.update-edge.result == 'success' && (needs.sync-edge-to-normal.result == 'success' || needs.sync-edge-to-normal.result == 'skipped')
    uses: ./.github/workflows/update-build.yaml
    with:
      addon: carconnectivity-addon
    secrets: inherit

  autotag-normal:
    needs: update-normal
    if: always() && needs.update-normal.result == 'success'
    uses: ./.github/workflows/autotag.yml
    with:
      target: normal
    secrets: inherit

  build-normal:
    needs: update-normal
    if: always() && needs.update-normal.result == 'success'
    uses: ./.github/workflows/builder.yml
    with:
      addon: carconnectivity-addon
    secrets: inherit

  release-normal:
    needs: [autotag-normal, build-normal]
    if: always() && needs.autotag-normal.result == 'success' && needs.build-normal.result == 'success'
    uses: ./.github/workflows/pre-release.yml
    with:
      addon: carconnectivity-addon
      prerelease: false
    secrets: inherit
