name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      sync_edge_to_normal:
        description: 'Sync edge to normal before building'
        type: boolean
        default: false
        required: false

jobs:
  update-edge:
    uses: ./.github/workflows/update-build.yaml
    with:
      addon: carconnectivity-addon-edge
    secrets: inherit

  autotag-edge:
    needs: update-edge
    uses: ./.github/workflows/autotag.yml
    secrets: inherit

  build-edge:
    needs: update-edge
    uses: ./.github/workflows/builder.yml
    with:
      addon: carconnectivity-addon-edge
    secrets: inherit

  sync-edge-to-normal:
    if: inputs.sync_edge_to_normal
    needs: update-edge
    uses: ./.github/workflows/sync.yml
    secrets: inherit

  update-normal:
    if: inputs.sync_edge_to_normal
    needs: sync-edge-to-normal
    uses: ./.github/workflows/update-build.yaml
    with:
      addon: carconnectivity-addon
    secrets: inherit

  autotag-normal:
    if: inputs.sync_edge_to_normal
    needs: update-normal
    uses: ./.github/workflows/autotag.yml
    secrets: inherit

  build-normal:
    if: inputs.sync_edge_to_normal
    needs: update-normal
    uses: ./.github/workflows/builder.yml
    with:
      addon: carconnectivity-addon
    secrets: inherit
